### ISSUE TITLE
LengthFrameEncoding regression in DotNetty 0.4.7 (and v0.4.6)

### ISSUE THREAD

**Issue by Aaronontheweb** [Azure/DotNetty#360] opened 2018-02-15 15:25 UTC
Had a couple of bug reports about this from Akka.NET users, but this one makes it official:

https://github.com/akkadotnet/akka.net/issues/3327

Some of the changes that were introduced in DotNetty v0.4.7 appear to have caused length frame encoding to break down. This issue does not occur in DotNetty v0.4.6. @nayato can you push an official release to Github so I can see the diff between verisons?

**Comment by nayato** [comment] 2018-02-15 15:29
try this: https://github.com/Azure/DotNetty/compare/f5c2ea1339ba03274187f0367790dd813d030391...58a82a0e3c336ae7e9b771edf01666a2b06008a3

**Comment by Aaronontheweb** [comment] 2018-02-15 15:31
Thanks @nayato - looks like it's this PR that introduced the issue: https://github.com/Azure/DotNetty/pull/287

Based on the errors reported by the users in that Akka.NET issue I linked, it sure sounds like the frame encoding / decoding itself was corrupted. Did someone change a default from BigEndian to LittleEndian / equivalent somewhere?

**Comment by nayato** [comment] 2018-02-15 15:34
that wouldn't pass CI. any details beyond "breaks"?

**Comment by Aaronontheweb** [comment] 2018-02-15 15:36
> that wouldn't pass CI.

Not necessarily true. If I'm running an Akka.NET Cluster and some nodes are running v0.4.7 and others are running v0.4.6, if v0.4.7 introduced a wire incompatibility I'd only notice it upon upgrading one group of nodes at a time. The entire v0.4.7 test suite might pass because as far as I know it doesn't carry out any backwards compatibility testing with previous versions.

**Comment by Aaronontheweb** [comment] 2018-02-15 15:36
See the Akka.NET issue for the full error message et al.

**Comment by nayato** [comment] 2018-02-15 15:36
ah, yes, now I see.. there was an issue with casting to `short`.

**Comment by Aaronontheweb** [comment] 2018-02-15 15:37
Did https://github.com/Azure/DotNetty/pull/351 fix this then?

**Comment by nayato** [comment] 2018-02-15 15:40
hmmm... so we had an issue with prepender actually.

**Comment by Aaronontheweb** [comment] 2018-02-15 15:43
And just in-case it matters, here's how we setup our pipelines in Akka.Remote with DotNetty:

https://github.com/akkadotnet/akka.net/blob/7e2688f551e801f0769bf9d71364a0d48439d249/src/core/Akka.Remote/Transport/DotNetty/DotNettyTransport.cs#L310-L355

Maximum payload bytes defaults to ~100k or so.

**Comment by nayato** [comment] 2018-02-15 15:44
can you guys try with latest dev? just to see if there's something to investigate still vs "release the thing already"

**Comment by Aaronontheweb** [comment] 2018-02-15 15:49
Yep, sure we can - do you have a nightly build feed available or do we need to just build from source?

**Comment by nayato** [comment] 2018-02-15 15:53
`powershell .\build.ps1 --target=Nightly --targetversion=0.4.8` this should do it

**Comment by nayato** [comment] 2018-02-15 15:56
as we're talking about akka->akka comm I suppose prepender issue might be to blame, i.e. wrong value is encoded (smaller one), that number of bytes is taken, then random number follows (that is actually part of data) and it is bigger than supported.

**Comment by Aaronontheweb** [comment] 2018-02-15 15:59
Yeah, that sounds like it to me; the Akka.Remote users who've been reporting the issue described it as DotNetty logging the frame as something significantly larger than what the frame size could have possibly been.

**Comment by nayato** [comment] 2018-02-15 16:04
ok, so... how urgent is this?.. we have a few big things coming in. One is a breaking change so 0.5.0 is in cards.

**Comment by Aaronontheweb** [comment] 2018-02-15 16:14
Pretty urgent. Breaks anyone's app who upgrades to a new version of DotNetty.

**Comment by nayato** [comment] 2018-02-15 16:15
well, with the change above it won't run (by design). is that enough until you guys upgrade to 0.5.0?

**Comment by Aaronontheweb** [comment] 2018-02-15 16:17
> well, with the change above it won't run (by design)

It won't? We're just using an integer header. That won't work on dev either?

**Comment by nayato** [comment] 2018-02-15 16:30
It's a breaking change in code. I.e. once you pull it in, you'd have to make sure ichannelhandler impls have proper write method signature. If you try to upgrade to it without recompilation, it will probably break at runtime unless you don't hit incompatible calls of course.

**Comment by Aaronontheweb** [comment] 2018-02-15 16:31
I see. In that case we can probably wait for 0.5.0. What's the ETA on that?

**Comment by nayato** [comment] 2018-02-15 17:40
next week

**Comment by StormHub** [comment] 2018-02-20 02:44
@Aaronontheweb There are quite a few API level breaking changes, please let me know if you need some help migrating. BTW: I use Akka too :)

**Comment by Aaronontheweb** [comment] 2018-02-20 13:56
@StormHub awesome! I'll let you know if we need help.

**Comment by jannicklange** [comment] 2018-07-05 15:57
Will the 0.5.0 be released any time soon?
Or is the bug fixed in 0.4.8?

**Comment by Aaronontheweb** [comment] 2018-07-05 17:09
Bug is fixed in v0.4.8 - upgrade to Akka.NET v1.3.8 for it.

**Comment by Aaronontheweb** [comment] 2018-07-05 17:11
Whoops my bad - assumed this was the Akka Github 😛

**Comment by nayato** [comment] 2018-07-05 17:55
@Aaronontheweb np.
@jannicklange as Aaron mentioned, it is fixed in 0.4.8

**Closed by nayato** 2018-07-05 17:55 UTC

**Comment by jannicklange** [comment] 2018-07-06 07:48
Awesome! Thanks a lot 👍
